baseURL = 'https://business-central-tech-bites.netlify.app'
languageCode = 'en-us'
title = 'Business Central Tech Bites'
theme = './ananke'
menu = 'main'
staticDir = '/static'
pagesDir = '/content'

[params]
  favicon = '/Logo/business-central-logo.png' 

[[params.ananke_socials]]
  name = "github" 
  url = "https://github.com/Riki432"

[[params.ananke_socials]]
  name = "linkedin" 
  url = "www.linkedin.com/in/rahul-bansode-205a2492"

[[params.ananke_socials]]
  name = "instagram" 
  url = "https://www.instagram.com/call_me_riki/"

[[params.ananke_socials]]
  name = "twitter" 
  url = "https://twitter.com/Rahulba02385073"

[module]
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = './ananke'

