baseURL = 'https://tech-bites.netlify.app'
languageCode = 'en-us'
title = 'Tech Bites'
description = "Bite sized blogs about the stuff I've learned over the years!"
theme = './ananke'
menu = 'main'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[params]
  favicon =  '/Profile/profilePic.png' 
  site_logo =  '/Profile/profilePic.png'

[[params.ananke_socials]]
  name = "github" 
  url = "https://github.com/Riki432"

[[params.ananke_socials]]
  name = "linkedin" 
  url = "www.linkedin.com/in/rahul-bansode-205a2492"

[[params.ananke_socials]]
  name = "instagram" 
  url = "https://www.instagram.com/call_me_riki/"

[[params.ananke_socials]]
  name = "twitter" 
  url = "https://twitter.com/Rahulba02385073"

[module]
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = './ananke'